name: iOS Build and Deploy

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.22.1'

permissions:
  contents: read
  actions: write
  security-events: write
  id-token: write

jobs:
  build_ios:
    name: Build iOS App
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Create iOS build directory
      run: mkdir -p ios/build
    
    - name: Import Code Signing Certificates
      uses: apple-actions/import-codesign-certs@v2
      with:
        p12-file-base64: ${{ secrets.IOS_DISTRIBUTION_CERTIFICATE_P12 }}
        p12-password: ${{ secrets.IOS_DISTRIBUTION_CERTIFICATE_PASSWORD }}
      
    # Skip provisioning profile for now - build without signing
    # - name: Download Provisioning Profile
    #   uses: apple-actions/download-provisioning-profiles@v1
    #   with:
    #     bundle-id: 'com.kasdsadhj6.tetrisapp'
    #     issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
    #     api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
    #     api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
    
    - name: Build iOS App (Unsigned for Testing)
      run: |
        flutter build ios --release --no-codesign
        cd ios
        # Create unsigned archive for testing
        xcodebuild -workspace Runner.xcworkspace \
                   -scheme Runner \
                   -configuration Release \
                   -destination generic/platform=iOS \
                   -archivePath $PWD/build/Runner.xcarchive \
                   CODE_SIGNING_ALLOWED=NO \
                   archive
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-build
        path: ios/build/Runner.ipa/Runner.ipa
        retention-days: 30