name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.22.1'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build_and_deploy:
    name: Build and Deploy Web
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Build web
      run: flutter build web --release --base-href /tetris-app/
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web